In [1]:
import numpy as np

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

--> list_ is a python list while arra_list is a numpy array
'''

'Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code\nto print the data types of both the variables.\n\n--> list_ is a python list while arra_list is a numpy array\n'

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

In [8]:
array_list.dtype

dtype('<U1')

In [9]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
'''
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
'''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
'''
array_list = np.array(object = list_, dtype = int)

In [12]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
#There will be difference in the data type of the elements present in both the variables list_ and array_list.
#The data type of each element of array_list will be integer.

In [15]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [16]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [17]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
'''
num_array.shape

(2, 3)

In [19]:
num_array.size

6

In [20]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
'''
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
'''
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])